# action.yml
name: 'RFS Enumeration'
description: 'Greet someone and record the time'
inputs:
  domain:  # id of input
    description: 'Who to greet'
    required: true
    default: 'AppSec'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.domain }}
